### PR TITLE
Fix NPE if mCameraDevice == null

### PR DESCRIPTION
**Pull request by gubiq**

### CODE REVIEW

**Comment by gubiq** [comment]
Oder liege ich hier falsch, @codeworkx ?

**Comment by NotTsunami** [comment]
Use Gerrit :)

**Comment by ZdrowyGosciu** [comment]
https://github.com/CyanogenMod/android_packages_apps_Snap/commit/bc69af7c6e8683594bb74c5211d086d3a3f17797 :yum:

**Comment by NotTsunami** [comment]
Didn't even see it. This can be closed then @gubiq

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.org/wiki/Howto:_Gerrit

Thanks!

**Pull request closed without merging**
